name: Main workflow
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        ## using latest LTS releases
        dotnet: [ '2.1.14', '3.1.0' ]

    name: Dotnet ${{ matrix.dotnet }} on OS ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Unit Tests
        run: dotnet test
      ## TODO: Converage and save to artifacts.

